---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: hugo/content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: hugo/content/lessons
  label: Lessons
  create: all
  match: "**/*"
- type: directory
  path: hugo/content/sermons
  label: Sermons
  create: all
  match: "**/*"
- type: directory
  path: hugo/content/articles
  label: Articles
  create: all
  match: "**/*"
- type: directory
  path: hugo/content/studies
  label: Studies
  create: all
  match: "**/*"
upload_dir: KingstonChurch
public_path: https://res.cloudinary.com/dy3wlzuye/video/upload/v1/KingstonChurch
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.57.1
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.57.1
